version: 2.1

orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

commands:
  install_aws:
    steps:
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - run: unzip awscliv2.zip
      - run: sudo ./aws/install
      - run: aws --version
        
jobs:
  build_deploy:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - run: npm i
      - run: npm run install
      - run: npm run build
      - aws-elastic-beanstalk/setup
      - run: eb init udagram -r $AWS_DEFAULT_REGION -p node.js
      - run: npm run deploy:api
      
  # debloy:
  #   docker:
  #     - image: cimg/node:16.13.1
  #   steps: 
  #     - install_aws
      # - install_eb
      # - run: cd udagram && npm run deploy


workflows:
  build_and_deploy:
    jobs:
      - build_deploy:
          context: udagram
      # - aws-elastic-beanstalk/deploy:
      #       app-dir: ./udagram/udagram-api 
      #       application-name: udagram 
      #       environment-name: udagram-api 
      #       platform-version: node.js
      #       context: udagram
      #       requires:
      #         - build
      # - deploy:
        # requires:
        #   - build