version: 2.1
executors:
  docker:
    docker:
      - image: cimg/node:stable
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  my-job-name:
    executor: docker
    steps:
      - checkout
      - run: |
          # echo Hello, World!
workflows:
  my-custom-workflow:
    jobs:
      - my-job-name