version: 2.1

orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

        
jobs:
  build:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - run: cd udagram
      - run: npm i
      - run: pwd
      - run: npm run install 
      - run: npm run build
      - run: pwd
  # debloy:
  #   docker:
  #     - image: cimg/node:16.13.1
  #   steps: 
  #     - install_aws
      # - install_eb
      # - run: cd udagram && npm run deploy


workflows:
  build_and_deploy:
    jobs:
      - build:
          context: udagram
      - aws-elastic-beanstalk/deploy:
            app-dir: ./udagram/udagram-api 
            application-name: udagram 
            environment-name: udagram-api 
            platform-version: node.js
            context: udagram
            requires:
              - build
      # - deploy:
        # requires:
        #   - build