version: 2.1

orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

commands:
  install_aws: # Installs AWS CLI
    steps:
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
      - run: unzip awscliv2.zip
      - run: sudo ./aws/install
        
jobs:
  build_deploy:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout # Retrieves source code
      - run: npm i # Installs root, front-end & api packages
      - run: npm run build # Builds front-end & api
      - aws-elastic-beanstalk/setup # Sets up EB CLI
      - install_aws # Install AWS CLI to deploy frontend to S3
      - run:
          name: Prepare api for deployment
          command: |
            cd udagram/udagram-api
            eb init udagram -r $AWS_DEFAULT_REGION -p node.js
            eb setenv AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - run: npm run deploy # Deploys front-end & api



workflows:
  build_and_deploy:
    jobs:
      - build_deploy:
          context: udagram # Uses secret env. variable declared in udagram