version: 2.1

orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

commands:
  install_aws:
    steps:
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - run: unzip awscliv2.zip
      - run: sudo ./aws/install
      - run: aws --version
  install_eb:
    steps:
      - aws-elastic-beanstalk/setup
        
jobs:
  build:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - install_aws
      - install_eb
      # - run: cd udagram && npm i && npm run install && npm run build
      # - run: cd udagram && eb init --region us-east-1 --platform node.js udagram && npm run deploy:api
  # debloy:
  #   docker:
  #     - image: cimg/node:16.13.1
  #   steps: 
  #     - install_aws
      # - install_eb
      # - run: cd udagram && npm run deploy


workflows:
  build_and_deploy:
    jobs:
      - build:
          context: udagram
      - aws-elastic-beanstalk/deploy:
            app-dir: ./udagram/udagram-api 
            application-name: udagram 
            environment-name: udagram-api 
            platform-version: node.js
            context: udagram
            requires:
              - build
      # - deploy:
        # requires:
        #   - build