version: 2.1

commands:
  install_aws:
    steps:
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - run: unzip awscliv2.zip
      - run: sudo ./aws/install
      - run: aws --version
        

jobs:
  build:
    docker:
      - image: cimg/node:16.13.1
    steps:
      - checkout
      - install_aws
      - run: cd udagram && npm run install && npm run build
      - run: cd udagram && npm run deploy
  # debloy:
  #   docker:
  #     - image: cimg/node:16.13.1
  #   steps: 
  #     - install_aws
      # - install_eb
      # - run: cd udagram && npm run deploy


workflows:
  build_and_deploy:
    jobs:
      - build
      # - deploy:
        # requires:
        #   - build